# generate-update-info.yaml
# Author: Pete Pickerill
# Description:
#   This flow runs several Liquibase commands to generate information that could be usefil for review, auditing
#   and troubleshooting purposes.  It will run in all shared pipeline environments from CI onward. It is not
#   required in development environments
stages:

  tagAndInspectDatabase:
  # Tag database current state
    actions:
    - type: liquibase
      command: tag
      cmdArgs: {tag: "GHA-TAG"}

  # Run verbose status to capture change history 
    - type: liquibase
      command: status
      cmdArgs: {verbose: true}

  # Generate SQL that will be executed during update
    - type: liquibase
      command: updateSql
      cmdArgs: {}