# validate-changes-update-db.yaml
# Author: Pete Pickerill
# Description:
#   This flow runs several Liquibase commands to generate information that could be usefil for review, auditing
#   and troubleshooting purposes.  It will run in all shared pipeline environments from CI onward. It is not
#   required in development environments
# How to use: liquibase flow --flow-file=validate-changes-update-db.yaml

stages:
  validateChangelog:
  # Run validate on Repo Changelog
    actions:
    - type: liquibase
      command: validate
      cmdArgs: {}

  # Get Quality Checks Repo
    - type: shell 
      command: git clone github5:liquibase/lpl_rules.git rules
      cmdArgs: {}

  # Copy Checks from Centralized Repo to current project
    - type: shell 
      command: xcopy /s/e/y rules\mongodb\QualityChecks\liquibase.checks-settings.conf .
      cmdArgs: {}

  # Run Checks on Repo Changelog
    - type: liquibase
      command: checks run --checks-scope=changelog
      cmdArgs: {}
  
  generateUpdateInfo:
    actions:
    - type: liquibase
      # Run everywhere but DEV
      if: "${LB_FLOW_ENV} != DEV"
      command: flow
      cmdArgs: {flow-file: "${LB_FLOW_DIR}/generate-update-info.yaml"}


  liquibaseUpdate:
  # Run Update on Latest Repo State
    actions:
    - type: liquibase
      command: update
      cmdArgs: {}
